camera_name: d455
camera_namespace: front
enable_color: true
enable_depth: true
# enable_infra: true
# enable_infra1: true
# enable_infra2: true
enable_sync: true
enable_rgbd: true
enable_gyro: true
enable_accel: true
# unite_imu_method: 2 # linear interpolation
pointcloud.enable: true
align_depth.enable: true
colorizer.enable: true
base_frame_id: d455_link
